// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdlJIZgG6i_bEtCajS-b6Sa8odDuOV45w',
    appId: '1:603026748720:web:2e91bbde35fee99b1a84f5',
    messagingSenderId: '603026748720',
    projectId: 'tuks-tutor',
    authDomain: 'tuks-tutor.firebaseapp.com',
    storageBucket: 'tuks-tutor.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_Q5D-JdRe2oq88yMMrGO9fSWp_rXHoxk',
    appId: '1:603026748720:android:c812607f9f731a271a84f5',
    messagingSenderId: '603026748720',
    projectId: 'tuks-tutor',
    storageBucket: 'tuks-tutor.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8ZxTgjEeveVVBh87d1mAjCuiKhSR_QQg',
    appId: '1:603026748720:ios:6696a0ed5fbbe05f1a84f5',
    messagingSenderId: '603026748720',
    projectId: 'tuks-tutor',
    storageBucket: 'tuks-tutor.appspot.com',
    iosBundleId: 'com.example.tuksTutorDev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8ZxTgjEeveVVBh87d1mAjCuiKhSR_QQg',
    appId: '1:603026748720:ios:6696a0ed5fbbe05f1a84f5',
    messagingSenderId: '603026748720',
    projectId: 'tuks-tutor',
    storageBucket: 'tuks-tutor.appspot.com',
    iosBundleId: 'com.example.tuksTutorDev',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdlJIZgG6i_bEtCajS-b6Sa8odDuOV45w',
    appId: '1:603026748720:web:77f52a7d8156febb1a84f5',
    messagingSenderId: '603026748720',
    projectId: 'tuks-tutor',
    authDomain: 'tuks-tutor.firebaseapp.com',
    storageBucket: 'tuks-tutor.appspot.com',
  );
}
